apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-{{ .Chart.Name }}
  labels:
    name: {{ .Release.Name }}-{{ .Chart.Name }}
    app: {{ .Release.Name }}-{{ .Chart.Name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Release.Name }}-{{ .Chart.Name }}
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-{{ .Chart.Name }}
    spec:
      containers:
        - image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          name: {{ .Release.Name }}-{{ .Chart.Name }}
          resources:
          {{- toYaml .Values.resources | nindent 12 }}
          envFrom:
            - configMapRef:
                name: {{ .Release.Name }}-{{ .Chart.Name }}-cm
            - secretRef:
            {{- if and .Values.ow.apiKey .Values.ow.secretRef}}
              {{- fail "cannot set both .ow.apiKey and .ow.secretRef"}}
            {{- else if and (empty .Values.ow.apiKey) (empty .Values.ow.secretRef) }}
              {{- fail "you need to set either .ow.apiKey or .ow.apiKey" }}
            {{- end}}
            {{- if and .Values.ow.secretRef (not .Values.ow.apiRef) }}
                name: {{ .Values.ow.secretRef }}
            {{- else }}
                name: {{ .Release.Name }}-{{ .Chart.Name }}-secret
            {{- end }}
          env:
            {{- range .Values.env_vars }}
            - name: {{ .name }}
              value: {{ .value }}
          {{- end }}